### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xrndf** [srakadotcom/napierdalanie3-final#4]
Ogolnie to crashuje przy wlaczaniu clienta
@?@# Game crashed! Crash report could not be saved. #@?@#
INFO abstract * abstract + , ? try else * $ ! final false ? public & synchronized finally false ! throw ^ ` transient throws ' 4 = 8 continue final instanceof strictfp " void & native while " 6 4 float while catch catch 6 private instanceof & super 6 case transient interface Stopping!
java.lang.Exception: called unload OpenGL
        at internal.org.lwjgl.opengl.GLContext.unloadOpenGLLibrary(?\_(?)_/?:1218)
        at internal.org.lwjgl.opengl.WindowsDisplayPeerInfo.destroy(?\_(?)_/?:228)
        at internal.org.lwjgl.opengl.DrawableGL.destroy(?\_(?)_/?:402)
        at internal.org.lwjgl.opengl.Display$5.destroy(?\_(?)_/?:2481)
        at internal.org.lwjgl.opengl.Display.destroy(?\_(?)_/?:3264)
        at abstract * abstract + , ? try else * $ ! final false ? public & synchronized finally false ! throw ^ ` transient throws ' 4 = 8 continue final instanceof strictfp " void & native while " 6 4 float while catch catch 6 private instanceof & super 6 case transient interface.1 case(?\_(?)_/?:3540)
        at abstract * abstract + , ? try else * $ ! final false ? public & synchronized finally false ! throw ^ ` transient throws ' 4 = 8 continue final instanceof strictfp " void & native while " 6 4 float while catch catch 6 private instanceof & super 6 case transient interface.protected =(?\_(?)_/?:1557)
        at net.minecraft.client.main.Main.main(?\_(?)_/?:363)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Start.main(Start.java:29)

**Comment by Memexurer** [comment]
jaaa pierdoleeeeeeeeeeee co ja mmam zrobci tera

**Comment by Xrndf** [comment]
> jaaa pierdoleeeeeeeeeeee co ja mmam zrobci tera

naprawic, albo chociaz powiedziec w czym jest problem

**Comment by Xrndf** [comment]
bo za chuja nie wiem co powoduje crasha

**Comment by Memexurer** [comment]
sprobuj zaaktualizowac klase NettyHandlers i Transform, moze panowie z bp zmienili jakies nazwy zeby te proxy nie dzialalo, idk...

**Comment by Memexurer** [comment]
[xd.zip](https://github.com/srakadotcom/napierdalanie3-final/files/11666351/xd.zip)

**Comment by Memexurer** [comment]
sprobuj tego uzyc, znalazlem to tera u sieibe na puplicie
